name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: nigeltho12
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
