name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    name: Generate GitHub Contribution Snake
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: nigeltho12
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Upload SVG to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
